/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'paymentStatus' : PaymentStatus,
  'bookingId' : string,
  'name' : string,
  'createdAt' : bigint,
  'ticketCount' : bigint,
  'email' : string,
  'checkedIn' : boolean,
  'phone' : string,
  'upiTxnId' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkInBooking' : ActorMethod<[string], boolean>,
  'createBooking' : ActorMethod<
    [string, string, string, string, [] | [bigint]],
    string
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getBookingsByPaymentStatus' : ActorMethod<[PaymentStatus], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchBookings' : ActorMethod<[string], Array<Booking>>,
  'updatePaymentStatus' : ActorMethod<[string, PaymentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];