/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'bookingId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'ticketCount' : IDL.Nat,
  'email' : IDL.Text,
  'checkedIn' : IDL.Bool,
  'phone' : IDL.Text,
  'upiTxnId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkInBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Text],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getBookingsByPaymentStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'bookingId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'ticketCount' : IDL.Nat,
    'email' : IDL.Text,
    'checkedIn' : IDL.Bool,
    'phone' : IDL.Text,
    'upiTxnId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkInBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Text],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getBookingsByPaymentStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchBookings' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };